apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  DOTNET_ENVIRONMENT: "Production"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "Pokemons"
  POSTGRES_HOST_AUTH_METHOD: "md5"
  POSTGRES_INITDB_ARGS: "--auth=md5"
  POSTGRES_MAX_CONNECTIONS: "500"
  MAX_CLIENT_CONN: "500"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_USER: "postgres"
  POOL_MODE: "transaction"
  ADMIN_USERS: "postgres,admin"
  ConnectionStrings__Database: "User Id=postgres;Password=3jp5xbbd;Host=postgres;Port=5432;Database=Pokemons;Pooling=true;MaxPoolSize=200;CommandTimeout=180;Timeout=300;"
  ConnectionStrings__Redis: "redis:6379"
  BotOption__WebAppLink: "https://cix-lilac.vercel.app/"
