services: 
  api:
    image: moonlization/api
    build:
      context: ..
      dockerfile: Pokemons/Dockerfile
    env_file: .env
    ports:
      - 5254:8080
    depends_on: 
      - pgbouncer
      - rabbitmq
  
  bot:
    image: moonlization/bot
    build:
      context: ..
      dockerfile: PokemonsBot/Dockerfile
    env_file: .env
    ports:
      - 5010:8080
    depends_on: 
      - api
      - rabbitmq

  postgres:
    image: postgres:latest
    env_file: .env
    volumes:
      - pokemons_data:/var/lib/postgresql/data
  
  pgbouncer:
    image: edoburu/pgbouncer:latest
    env_file: .env
    ports:
      - 5432:5432
    depends_on: 
      - postgres
  
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: always
    networks:
      - default
        
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - default

volumes: 
  pokemons_data:
    
networks:
  default:
    driver: bridge